global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'events-spring-app'
    metrics_path: '/events/actuator/prometheus'
    static_configs:
      - targets: ['events-app:8089']
        labels:
          application: 'events-project'

