global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'events-spring-app'
    metrics_path: '/events/actuator/prometheus'
    static_configs:
      - targets: ['172.21.0.5:8089']
        labels:
          application: 'events-project'
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8787']
        labels:
          application: 'cadvisor'

