global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'events-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/events/actuator/prometheus'
    static_configs:
      - targets: ['events-app:8089']
        labels:
          application: 'events-project'
          environment: 'production'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
        labels:
          service: 'mysql-database'

